# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{sg-ruby}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Dofter"]
  s.date = %q{2010-05-12}
  s.email = %q{dan@dofter.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/simple_geo.rb",
     "lib/simple_geo/client.rb",
     "lib/simple_geo/connection.rb",
     "lib/simple_geo/endpoint.rb",
     "lib/simple_geo/hash_utils.rb",
     "lib/simple_geo/record.rb",
     "lib/simplegeo.rb",
     "sg-ruby.gemspec",
     "spec/client_spec.rb",
     "spec/fixtures/contains.json",
     "spec/fixtures/get_density_by_day.json",
     "spec/fixtures/get_density_by_hour.json",
     "spec/fixtures/get_history.json",
     "spec/fixtures/get_nearby.json",
     "spec/fixtures/get_record.json",
     "spec/fixtures/get_records.json",
     "spec/fixtures/layer_info.json",
     "spec/fixtures/nearby_address.json",
     "spec/fixtures/no_such_record.json",
     "spec/fixtures/nonetype_not_iterable.json",
     "spec/fixtures/overlaps.json",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/archfear/sg-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A SimpleGeo Ruby Client}
  s.test_files = [
    "spec/client_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<oauth>, [">= 0.4.0"])
      s.add_runtime_dependency(%q<json_pure>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_development_dependency(%q<fakeweb>, [">= 1.2.0"])
    else
      s.add_dependency(%q<oauth>, [">= 0.4.0"])
      s.add_dependency(%q<json_pure>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.0"])
      s.add_dependency(%q<fakeweb>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<oauth>, [">= 0.4.0"])
    s.add_dependency(%q<json_pure>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.0"])
    s.add_dependency(%q<fakeweb>, [">= 1.2.0"])
  end
end

